<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ru_RU">
<context>
    <name>SplashScreenClass</name>
    <message>
        <location filename="../SplashScreen.ui" line="69"/>
        <source>#terminal_not_available</source>
        <translation>Терминал временно недоступен</translation>
    </message>
    <message>
        <location filename="../SplashScreen.ui" line="134"/>
        <source>#updater_state_message</source>
        <translation>Проводятся технические работы</translation>
    </message>
</context>
<context>
    <name>UpdaterApp</name>
    <message>
        <location filename="../UpdaterApp.cpp" line="96"/>
        <source>#error_run_from_temp_dir</source>
        <translation>Ошибка запуска updater из временной папки</translation>
    </message>
    <message>
        <location filename="../UpdaterApp.cpp" line="97"/>
        <source>#error_connection_to_guard</source>
        <translation>Ошибка соединения с guard.exe</translation>
    </message>
    <message>
        <location filename="../UpdaterApp.cpp" line="98"/>
        <source>#error_unknown_command</source>
        <translation>Неизвестная команда</translation>
    </message>
    <message>
        <location filename="../UpdaterApp.cpp" line="99"/>
        <source>#error_second_instance</source>
        <translation>Запуск второй копии updater</translation>
    </message>
    <message>
        <location filename="../UpdaterApp.cpp" line="100"/>
        <source>#error_unknown</source>
        <translation>Неизвестная ошибка</translation>
    </message>
    <message>
        <location filename="../UpdaterApp.cpp" line="101"/>
        <source>#error_network</source>
        <translation>Сетевая ошибка</translation>
    </message>
    <message>
        <location filename="../UpdaterApp.cpp" line="102"/>
        <source>#error_parse_response</source>
        <translation>Ошибка обработки ответа сервера обновления</translation>
    </message>
    <message>
        <location filename="../UpdaterApp.cpp" line="103"/>
        <source>#error_deploy</source>
        <translation>Ошибка копирования файлов</translation>
    </message>
    <message>
        <location filename="../UpdaterApp.cpp" line="104"/>
        <source>#error_aborted</source>
        <translation>Прерван внешним процессом</translation>
    </message>
    <message>
        <location filename="../UpdaterApp.cpp" line="105"/>
        <source>#error_update_blocked</source>
        <translation>Обновление заблокировано</translation>
    </message>
    <message>
        <location filename="../UpdaterApp.cpp" line="106"/>
        <location filename="../UpdaterApp.cpp" line="349"/>
        <source>#error_check_integrity</source>
        <translation>Целостность дистрибутива нарушена. Кол-во отличий: %1. Выполните команду обновления ПО</translation>
    </message>
</context>
</TS>
